/*
 * @Author: lizheng
 * @Date: 2021-01-13 14:36:25
 * @LastEditTime: 2021-03-23 15:03:45
 * @LastEditors: Please set LastEditors
 * @Description:推广模块用户的常量（表格字段、字段映射）
 * @Description： 定义常量映射的值请用大写英文字母
 * @FilePath: \ads\pages\promotion\contant.js
 */

// 公共的表格字段
export const commonColumn = [
  {
    title: '转化数',
    dataIndex: 'convert',
    width: 100,
    sorter: (a, b) => a.convert - b.convert,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '转化成本',
    dataIndex: 'convertCost',
    width: 120,
    sorter: (a, b) => a.convertCost - b.convertCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '转化率',
    dataIndex: 'convertRate',
    width: 100,
    sorter: (a, b) => a.convertRate - b.convertRate,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => `${text}%`,
  },
  {
    title: '深度转化数',
    dataIndex: 'deepConvert',
    width: 120,
    sorter: (a, b) => a.deepConvert - b.deepConvert,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '深度转化成本',
    dataIndex: 'deepConvertCost',
    width: 130,
    sorter: (a, b) => a.deepConvertCost - b.deepConvertCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '深度转化率',
    dataIndex: 'deepConvertRate',
    width: 120,
    sorter: (a, b) => a.deepConvertRate - b.deepConvertRate,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => `${text}%`,
  },
  {
    title: '转化数（计费时间）',
    dataIndex: 'attributionConvert',
    width: 180,
    sorter: (a, b) => a.attributionConvert - b.attributionConvert,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '转化成本（计费时间）',
    dataIndex: 'attributionConvertCost',
    width: 200,
    sorter: (a, b) => a.attributionConvertCost - b.attributionConvertCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '深度转化数（计费时间）',
    dataIndex: 'attributionDeepConvert',
    width: 200,
    sorter: (a, b) => a.attributionDeepConvert - b.attributionDeepConvert,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '深度转化成本（计费时间）',
    dataIndex: 'attributionDeepConvertCost',
    width: 220,
    sorter: (a, b) => a.attributionDeepConvertCost - b.attributionDeepConvertCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '预估转化(计费时间)',
    width: 170,
    groupId: 'AdGroupSetting',
    dataIndex: '2222',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '消耗',
    width: 80,
    dataIndex: 'cost',
    sorter: (a, b) => a.cost - b.cost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '展示数',
    width: 80,
    dataIndex: 'show',
    sorter: (a, b) => a.show - b.show,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '平均千次展现费用',
    dataIndex: 'avgShowCost',
    width: 160,
    sorter: (a, b) => a.avgShowCost - b.avgShowCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '点击数',
    dataIndex: 'click',
    width: 80,
    sorter: (a, b) => a.click - b.click,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '点击率',
    dataIndex: 'ctr',
    width: 80,
    sorter: (a, b) => a.ctr - b.ctr,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => `${text}%`,
  },
  {
    title: '平均点击单价',
    dataIndex: 'avgClickCost',
    width: 140,
    sorter: (a, b) => a.avgClickCost - b.avgClickCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意电话按钮点击',
    dataIndex: 'advancedCreativePhoneClick',
    width: 200,
    sorter: (a, b) => a.advancedCreativePhoneClick - b.advancedCreativePhoneClick,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意在线咨询点击',
    dataIndex: 'advancedCreativeCounselClick',
    width: 200,
    sorter: (a, b) => a.advancedCreativeCounselClick - b.advancedCreativeCounselClick,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意表单按钮点击',
    dataIndex: 'advancedCreativeFormClick',
    width: 200,
    sorter: (a, b) => a.advancedCreativeFormClick - b.advancedCreativeFormClick,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意表单提交',
    dataIndex: 'advancedCreativeFormSubmit',
    width: 160,
    sorter: (a, b) => a.advancedCreativeFormSubmit - b.advancedCreativeFormSubmit,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意卡券领取',
    dataIndex: 'advancedCreativeCouponAddition',
    width: 160,
    sorter: (a, b) => a.advancedCreativeCouponAddition - b.advancedCreativeCouponAddition,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
]

// 推广模块  广告组字段
export const AdGroupcolumns = [
  {
    title: '',
    dataIndex: 'status',
    key: 'adStatus',
    width: 60,
    align: 'center',
    fixed: 'left',
    scopedSlots: { customRender: 'adStatus' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '广告组名称',
    width: 250,
    fixed: 'left',
    dataIndex: 'name',
    ellipsis: true,
    groupId: 'AdGroupSetting',
    scopedSlots: { customRender: 'name' },
    customCell: (record) => ({
      on: {
        mouseenter: () => (record.isShowEditIcon = true),
        mouseleave: () => (record.isShowEditIcon = false),
      },
    }),
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '操作',
    width: 120,
    fixed: 'left',
    dataIndex: 'operate',
    scopedSlots: { customRender: 'operate' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '推广目的',
    width: 120,
    ellipsis: true,
    dataIndex: 'landingType',
    groupId: 'AdGroupSetting',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => LANDING_TYPE[text],
  },
  {
    title: '广告组类型',
    width: 100,
    dataIndex: 'campaignType',
    ellipsis: true,
    groupId: 'AdGroupSetting',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? (text === 'FEED' ? '信息流' : '其它') : '--'),
  },
  {
    title: '组预算',
    width: 100,
    dataIndex: 'budget',
    ellipsis: true,
    groupId: 'AdGroupSetting',
    scopedSlots: { customRender: 'budget' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '广告组ID',
    width: 180,
    groupId: 'AdGroupSetting',
    ellipsis: true,
    dataIndex: 'id',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '广告组状态',
    width: 100,
    ellipsis: true,
    dataIndex: 'status',
    groupId: 'AdGroupSetting',
    scopedSlots: { customRender: 'status' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '组否定词',
    width: 120,
    ellipsis: true,
    dataIndex: 'negativeWords',
    groupId: 'AdGroupSetting',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  ...commonColumn,
]

// 推广模块 计划字段
export const planColumns = [
  {
    title: '',
    dataIndex: 'optStatus',
    key: 'planStatus',
    width: 60,
    align: 'center',
    fixed: 'left',
    scopedSlots: { customRender: 'planStatus' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '广告计划名称',
    width: 250,
    fixed: 'left',
    dataIndex: 'name',
    groupId: 'AdGroupSetting',
    scopedSlots: { customRender: 'name' },
    customCell: (record) => ({
      on: {
        mouseenter: () => (record.isShowEditIcon = true),
        mouseleave: () => (record.isShowEditIcon = false),
      },
    }),
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa', height: '50px' } }),
  },
  {
    title: '操作',
    width: 120,
    fixed: 'left',
    dataIndex: 'operate',
    scopedSlots: { customRender: 'operate' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '广告组名称',
    width: 250,
    dataIndex: 'campaignName',
    groupId: 'AdGroupSetting',
    scopedSlots: { customRender: 'campaignName' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa', height: '50px' } }),
  },
  {
    title: '计划创建时间',
    width: 250,
    dataIndex: 'adCreateTime',
    groupId: 'AdGroupSetting',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa', height: '50px' } }),
  },
  {
    title: '推广目的',
    width: 120,
    dataIndex: 'landingType',
    groupId: 'AdGroupSetting',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? LANDING_TYPE[text] : '--'),
  },
  {
    title: '广告组类型',
    width: 120,
    dataIndex: 'campaignType',
    groupId: 'AdGroupSetting',
    sorter: (a, b) => a.age - b.age,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? (text === 'FEED' ? '信息流' : '其它') : '--'),
  },
  {
    title: '广告组ID',
    width: 150,
    groupId: 'AdGroupSetting',
    dataIndex: 'campaignId',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '计划状态',
    width: 120,
    groupId: 'AdGroupSetting',
    dataIndex: 'status',
    scopedSlots: { customRender: 'status' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '计划预算(元)',
    width: 120,
    groupId: 'AdGroupSetting',
    dataIndex: 'budget',
    ellipsis: true,
    scopedSlots: { customRender: 'budget' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customCell: (record) => ({
      on: {
        mouseenter: () => (record.isShowEditBudgetIcon = true),
        mouseleave: () => (record.isShowEditBudgetIcon = false),
      },
    }),
  },
  {
    title: '出价(元)',
    width: 100,
    groupId: 'AdGroupSetting',
    dataIndex: 'bid',
    scopedSlots: { customRender: 'bid' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customCell: (record) => ({
      on: {
        mouseenter: () => (record.isShowEditBidIcon = true),
        mouseleave: () => (record.isShowEditBidIcon = false),
      },
    }),
  },
  {
    title: '计划ID',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'adId',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '投放场景-竞价策略',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'flowControlMode',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? FLOW_CONTROL_MODE[text] : '--'),
  },
  {
    title: '投放范围',
    width: 120,
    groupId: 'AdGroupSetting',
    dataIndex: 'deliveryRange',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? DELIVERY_RANGE[text] : ''),
  },
  {
    title: '投放时间',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'deliveryTime',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text, { startTime, endTime }) => (startTime ? `${startTime}至${endTime}` : '--'),
  },
  {
    title: '下载方式',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'downloadType',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '下载链接',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'downloadUrl',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '落地页链接',
    width: 260,
    ellipsis: true,
    groupId: 'AdGroupSetting',
    dataIndex: 'externalUrl',
    scopedSlots: { customRender: 'externalUrl' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '应用下载详情页链接',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: '1111',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '转化目标',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'convertId',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '深度转化出价（元）',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'deepCpabid',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '深度转化目标',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'deepConvertId',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: 'ROI系数',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'roiGoal',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '转化监测地址',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'convertMonitorUrl',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '投放位置',
    width: 150,
    groupId: 'AdGroupSetting',
    dataIndex: 'inventoryType',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? INVENTORY_TYPE[text] : '--'),
  },
  {
    title: '计划诊断',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'conclusion',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '自动规则',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'autoRule',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  {
    title: '计划否定词',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'negativeWords',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? text : '--'),
  },
  ...commonColumn,
]

// 创意字段 column
export const ideaColumns = [
  {
    title: '开关',
    dataIndex: 'optStatus',
    key: 'optStatus',
    fixed: 'left',
    width: 70,
    scopedSlots: { customRender: 'optStatus' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: 'ID',
    dataIndex: 'creativeId',
    fixed: 'left',
    width: 156,
    ellipsis: true,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '广告创意',
    dataIndex: 'title',
    fixed: 'left',
    width: 360,
    scopedSlots: { customRender: 'advertisingTitle' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '广告组名称',
    dataIndex: 'campaignName',
    width: 180,
    scopedSlots: { customRender: 'campaignNameTitle' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '推广目的',
    dataIndex: 'landingType',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    width: 150,
    customRender: (text) => (text ? LANDING_TYPE[text] : '--'),
  },
  {
    title: '广告组类型',
    dataIndex: 'campaignType',
    width: 120,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? advertisingsStatu[text] : '--'),
  },
  {
    title: '广告组ID',
    key: '广告组ID',
    dataIndex: 'campaignId',
    width: 180,
    sorter: (a, b) => a.campaignId - b.campaignId,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '计划名称',
    dataIndex: 'adName',
    width: 240,
    scopedSlots: { customRender: 'adNameSlot' },
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '计划ID',
    dataIndex: 'adId',
    width: 180,
    sorter: (a, b) => a.adId - b.adId,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '投放场景-竞价策略',
    dataIndex: 'flowControlMode',
    width: 180,
    sorter: (a, b) => a.flowControlMode - b.flowControlMode,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? FLOW_CONTROL_MODE[text] : '--'),
  },
  {
    title: '投放范围',
    dataIndex: 'deliveryRange',
    width: 120,
    ellipsis: true,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? DELIVERY_RANGE[text] : '--'),
  },
  {
    title: '投放时间',
    width: 200,
    groupId: 'AdGroupSetting',
    dataIndex: 'deliveryTime',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text, { startTime, endTime }) => (startTime ? `${startTime}至${endTime}` : '--'),
  },
  {
    title: '下载方式',
    dataIndex: 'downloadType',
    width: 180,
    sorter: (a, b) => a.downloadType - b.downloadType,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? DELIVERY_RANGE[text] : '--'),
  },
  {
    title: '下载链接',
    dataIndex: 'downloadUrl',
    width: 180,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    scopedSlots: { customRender: 'downloadUrlSlot' },
  },
  {
    title: '落地页链接',
    dataIndex: 'externalUrl',
    width: 180,
    sorter: (a, b) => a.externalUrl - b.externalUrl,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '应用下载详情页链接',
    dataIndex: 'webUrl',
    width: 180,
    customRender: (text) => (text ? DELIVERY_RANGE[text] : '--'),
  },
  {
    title: '转化目标',
    dataIndex: 'convertId',
    width: 180,
    sorter: (a, b) => a.convertId - b.convertId,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '转化监测地址',
    dataIndex: 'actionTrackUrl',
    width: 180,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? DELIVERY_RANGE[text] : '--'),
  },
  {
    title: '投放位置',
    width: 150,
    groupId: 'AdGroupSetting',
    dataIndex: 'inventoryType',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => (text ? INVENTORY_TYPE[text] : '--'),
  },
  {
    title: '广告创意状态',
    dataIndex: 'status',
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    width: 120,
    ellipsis: true,
    scopedSlots: { customRender: 'advertisingStatu' },
  },
  {
    title: '创意ID',
    key: '创意ID',
    dataIndex: 'creativeId',
    width: 180,
    sorter: (a, b) => a.creativeId - b.creativeId,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '转化数',
    dataIndex: 'convert',
    width: 100,
    sorter: (a, b) => a.convert - b.convert,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '转化成本',
    dataIndex: 'convertCost',
    width: 120,
    sorter: (a, b) => a.convertCost - b.convertCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '转化率',
    dataIndex: 'convertRate',
    width: 150,
    sorter: (a, b) => a.convertRate - b.convertRate,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => `${text}%`,
  },
  {
    title: '深度转化数',
    dataIndex: 'deepConvert',
    width: 150,
    sorter: (a, b) => a.deepConvert - b.deepConvert,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '深度转化成本',
    dataIndex: 'deepConvertCost',
    width: 150,
    sorter: (a, b) => a.deepConvertCost - b.deepConvertCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '深度转化率',
    dataIndex: 'deepConvertRate',
    width: 150,
    sorter: (a, b) => a.deepConvertRate - b.deepConvertRate,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => `${text}%`,
  },
  {
    title: '转化数（计费时间）',
    dataIndex: 'attributionConvert',
    width: 180,
    sorter: (a, b) => a.attributionConvert - b.attributionConvert,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '转化成本（计费时间）',
    dataIndex: 'attributionConvertCost',
    width: 210,
    sorter: (a, b) => a.attributionConvertCost - b.attributionConvertCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '深度转化数（计费时间）',
    dataIndex: 'attributionDeepConvert',
    width: 210,
    sorter: (a, b) => a.attributionDeepConvert - b.attributionDeepConvert,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '深度转化成本（计费时间）',
    dataIndex: 'attributionDeepConvertCost',
    width: 230,
    sorter: (a, b) => a.attributionDeepConvertCost - b.attributionDeepConvertCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '消耗',
    dataIndex: 'cost',
    width: 100,
    sorter: (a, b) => a.cost - b.cost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '展示数',
    dataIndex: 'show',
    width: 100,
    sorter: (a, b) => a.show - b.show,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '平均千次展现费用',
    dataIndex: 'avgShowCost',
    width: 180,
    sorter: (a, b) => a.avgShowCost - b.avgShowCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '点击数',
    dataIndex: 'click',
    width: 100,
    sorter: (a, b) => a.click - b.click,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '点击率',
    dataIndex: 'ctr',
    width: 100,
    sorter: (a, b) => a.ctr - b.ctr,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
    customRender: (text) => `${text}%`,
  },
  {
    title: '平均点击单价',
    dataIndex: 'avgClickCost',
    width: 180,
    sorter: (a, b) => a.avgClickCost - b.avgClickCost,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意电话按钮点击',
    dataIndex: 'advancedCreativePhoneClick',
    width: 200,
    sorter: (a, b) => a.advancedCreativePhoneClick - b.advancedCreativePhoneClick,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意在线咨询点击',
    dataIndex: 'advancedCreativeCounselClick',
    width: 200,
    sorter: (a, b) => a.advancedCreativeCounselClick - b.advancedCreativeCounselClick,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意表单按钮点击',
    dataIndex: 'advancedCreativeFormClick',
    width: 200,
    sorter: (a, b) => a.advancedCreativeFormClick - b.advancedCreativeFormClick,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意表单提交',
    dataIndex: 'advancedCreativeFormSubmit',
    width: 180,
    ellipsis: true,
    sorter: (a, b) => a.advancedCreativeFormSubmit - b.advancedCreativeFormSubmit,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
  {
    title: '附加创意卡券领取',
    dataIndex: 'advancedCreativeCouponAddition',
    width: 180,
    ellipsis: true,
    sorter: (a, b) => a.advancedCreativeCouponAddition - b.advancedCreativeCouponAddition,
    customHeaderCell: () => ({ style: { backgroundColor: '#f5f7fa' } }),
  },
]

// 自定义列 - checkbox
export const columnsList = [
  {
    parentLabel: '属性设置',
    href: '#attr',
    children: [
      {
        name: '广告组设置',
        id: 'adGroupSetting',
        checkboxList: [
          { checked: false, value: 'adGroupSetting', label: '全选' },
          { checked: false, value: 'campaignName', label: '广告组名称' },
          { checked: false, value: 'landingType', label: '推广目的' },
          { checked: false, value: 'campaignType', label: '广告组类型' },
          { checked: false, value: 'budget', label: '组预算' },
          { checked: false, value: 'id', label: '广告组ID' },
          { checked: false, value: 'adGroupStatus', label: '广告组状态' },
          { checked: false, value: 'negative', label: '组否定词' },
        ],
      },
      {
        name: '广告计划设置',
        id: 'adPlanSetting',
        checkboxList: [
          { checked: false, value: 'adPlanSetting', label: '全选' },
          { checked: false, value: 'planName', label: '计划名称' },
          { checked: false, value: 'planStatus', label: '计划状态' },
          { checked: false, value: 'planBudget', label: '计划预算（元）' },
          { checked: false, value: 'bid', label: '出价（元）' },
          { checked: false, value: 'adId', label: '计划ID' },
          { checked: false, value: 'flowControlMode', label: '投放场景-竞价策略' },
          { checked: false, value: 'deliveryRange', label: '投放范围' },
          { checked: false, value: 'deliveryTime', label: '投放时间' },
          { checked: false, value: 'downloadType', label: '下载方式' },
          { checked: false, value: 'downloadUrl', label: '下载链接' },
          { checked: false, value: 'externalUrl', label: '落地页链接' },
          { checked: false, value: 'appDownloadUrl', label: '应用下载详情页链接' },
          { checked: false, value: 'convertId', label: '转化目标' },
          { checked: false, value: 'deepCpabid', label: '深度转化出价（元）' },
          { checked: false, value: 'deepConvertId', label: '深度转化目标' },
          { checked: false, value: 'roiGoal', label: 'ROI系数' },
          { checked: false, value: 'convertMonitorUrl', label: '转化监测地址' },
          { checked: false, value: 'inventoryType', label: '投放位置' },
          { checked: false, value: 'conclusion', label: '计划诊断' },
          { checked: false, value: 'autoRule', label: '自动规则' },
          { checked: false, value: 'negativeWords', label: '计划否定词' },
        ],
      },
      {
        name: '创意设置',
        id: 'ideaSettting',
        checkboxList: [
          { checked: false, value: 'ideaSettting', label: '全选' },
          { checked: false, value: 'advertisingStatu', label: '广告创意状态' },
          { checked: false, value: 'creativeId', label: '创意ID' },
        ],
      },
    ],
  },
  {
    parentLabel: '效果指标',
    href: '#effect',
    children: [
      {
        name: '转化数据',
        id: 'convertData',
        checkboxList: [
          { checked: false, value: 'convertData', label: '全选' },
          { checked: false, value: 'convert', label: '转化数' },
          { checked: false, value: 'convertCost', label: '转化成本' },
          { checked: false, value: 'convertRate', label: '转化率' },
          { checked: false, value: 'deepConvert', label: '深度转化数' },
          { checked: false, value: 'deepConvertCost', label: '深度转化成本' },
          { checked: false, value: 'deepConvertRate', label: '深度转化率' },
        ],
      },
      {
        name: '转化数据（计费时间）',
        id: 'convertDataPayTime',
        checkboxList: [
          { checked: false, value: 'convertDataPayTime', label: '全选' },
          { checked: false, value: 'attributionConvert', label: '转化数（计费时间）' },
          { checked: false, value: 'attributionConvertCost', label: '转化成本（计费时间）' },
          { checked: false, value: 'attributionDeepConvert', label: '深度转化数（计费时间）' },
          {
            checked: false,
            value: 'attributionDeepConvertCost',
            label: '深度转化成本（计费时间）',
          },
          { checked: false, value: 'deepConvertRateTime', label: '深度转化率（计费时间）' },
          { checked: false, value: 'estimateConverTime', label: '预估转化（计费时间）' },
        ],
      },
      {
        name: '展现数据',
        id: 'displayData',
        checkboxList: [
          { checked: false, value: 'displayData', label: '全选' },
          { checked: false, value: 'cost', label: '消耗' },
          { checked: false, value: 'show', label: '展示数' },
          { checked: false, value: 'avgShowCost', label: '平均千次展现费用' },
          { checked: false, value: 'click', label: '点击数' },
          { checked: false, value: 'ctr', label: '点击率' },
          { checked: false, value: 'avgClickCost', label: '平均点击单价' },
        ],
      },
      {
        name: '附加创意',
        id: 'additionalCreativity',
        checkboxList: [
          { checked: false, value: 'additionalCreativity', label: '全选' },
          { checked: false, value: 'advancedCreativePhoneClick', label: '附加创意电话按钮点击' },
          { checked: false, value: 'advancedCreativeCounselClick', label: '附加创意在线咨询点击' },
          { checked: false, value: 'advancedCreativeFormClick', label: '附加创意表单按钮点击' },
          { checked: false, value: 'advancedCreativeFormSubmit', label: '附加创意表单提交' },
          { checked: false, value: 'advancedCreativeCouponAddition', label: '附加创意卡券领取' },
        ],
      },
    ],
  },
]

// 推广模块页面顶部 - 筛选条件模块的条件值
export const filterOptions = [
  {
    id: 'group-status',
    type: '组',
    options: [
      {
        label: '组状态',
        mode: 'default',
        vModel: 'groupStatus',
        option: [
          { label: '不限', value: 'CAMPAIGN_STATUS_ALL' },
          { label: '启用', value: 'CAMPAIGN_STATUS_ENABLE' },
          { label: '暂停', value: 'CAMPAIGN_STATUS_DISABLE' },
          { label: '删除', value: 'CAMPAIGN_STATUS_DELETE' },
          { label: '不限（包含已删除）', value: 'CAMPAIGN_STATUS_NOT_DELETE' },
        ],
      },
      {
        label: '推广目的',
        mode: 'multiple',
        vModel: 'promotionPurpose',
        option: [
          { label: '销售线索收集', value: 'CAMPAIGN_STATUS_ALL' },
          { label: '头条文章推广', value: 'CAMPAIGN_STATUS_ENABLE' },
          { label: '应用推广', value: 'CAMPAIGN_STATUS_DISABLE' },
          { label: '商品推广', value: 'CAMPAIGN_STATUS_DELETE' },
          { label: '商品目录推广', value: 'CAMPAIGN_STATUS_NOT_DELETE0' },
          { label: '门店推广', value: 'CAMPAIGN_STATUS_NOT_DELETE1' },
          { label: '抖音号推广', value: 'CAMPAIGN_STATUS_NOT_DELETE2' },
          { label: '电商店推广', value: 'CAMPAIGN_STATUS_NOT_DELETE3' },
        ],
      },
      {
        label: '组否定词',
        mode: 'default',
        vModel: 'negativeWord',
        option: [
          { label: '不限', value: 'CAMPAIGN_STATUS_ALL' },
          { label: '未设置否定词', value: 'CAMPAIGN_STATUS_ENABLE' },
          { label: '已设置否定词', value: 'CAMPAIGN_STATUS_DISABLE' },
        ],
      },
      {
        label: '广告主类型',
        mode: 'multiple',
        vModel: 'advertiserType',
        option: [
          // { label: '全选', value: 'CAMPAIGN_STATUS_ALL' },
          { label: '信息流广告', value: 'CAMPAIGN_STATUS_ENABLE' },
          { label: '搜索广告', value: 'CAMPAIGN_STATUS_DISABLE' },
        ],
      },
      {
        label: '投放模式',
        mode: 'default',
        vModel: 'deliveryMode',
        option: [
          { label: '不限', value: '不限' },
          { label: '标准投放', value: '投放中1' },
          { label: '管家投放', value: '投放中' },
        ],
      },
    ],
  },
  {
    id: 'plan',
    type: '计划',
    options: [
      {
        label: '计划状态',
        mode: 'default',
        vModel: 'planStatus',
        option: [
          { label: '不限', value: '不限' },
          { label: '投放中', value: '投放中1' },
          { label: '审核不通过', value: '投放中2' },
          { label: '不在投放时段', value: '投放中3' },
          { label: '已暂停', value: '投放中4' },
          { label: '已被广告组暂停', value: '投放中5' },
          { label: '广告计划超出预期', value: '6' },
          { label: '广告组超出预算', value: '7' },
          { label: '账号余额不足', value: '8' },
          { label: '新建审核中', value: '90' },
          { label: '修改审核中', value: '91' },
          { label: '计划新建', value: '19' },
          { label: '已删除', value: '92' },
          { label: '已完成', value: '93' },
          { label: '未达到投放时间', value: '94' },
          { label: '不限（包含已删除）', value: '95' },
        ],
      },
      {
        label: '计费方式',
        mode: 'multiple',
        vModel: 'payWay',
        option: [
          { label: 'CPM', value: '不限' },
          { label: 'CPC', value: '投放中1' },
          { label: 'oCPC', value: '投放中2' },
        ],
      },
      {
        label: '投放位置',
        mode: 'multiple',
        vModel: 'placement',
        option: [
          { label: '西瓜视频', value: '不限' },
          { label: '抖音火山版', value: '2' },
          { label: '抖音短视频', value: '1' },
          { label: '今日头条', value: '0' },
          { label: '穿山甲', value: '12' },
        ],
      },
      {
        label: '计划预算',
        mode: 'multiple',
        vModel: 'planBudget',
        option: [
          { label: '按日预算', value: '不限' },
          { label: '总预算', value: '2' },
        ],
      },
      {
        label: '计划否定词',
        mode: 'default',
        vModel: 'planNegativeWords',
        option: [
          { label: '不限', value: '不限' },
          { label: '未设置否定词', value: '1' },
          { label: '已设置否定词', value: '2' },
        ],
      },
      {
        label: '平台',
        mode: 'default',
        vModel: 'platform',
        option: [
          { label: '不限', value: '不限' },
          { label: 'IOS', value: 'IOS' },
          { label: 'Android', value: 'Android' },
          { label: 'PC', value: 'PC' },
        ],
      },
      {
        label: '大投计划',
        mode: 'default',
        vModel: 'isBigPut',
        option: [
          { label: '全部', value: '2' },
          { label: '是', value: '1' },
          { label: '否', value: '0' },
        ],
      },
    ],
  },
  {
    id: 'idea',
    type: '创意',
    options: [
      {
        label: '创意状态',
        mode: 'default',
        vModel: 'creativeState',
        option: [
          { label: '不限', value: '不限' },
          { label: '投放中', value: '投放中' },
          { label: '已暂停', value: '已暂停' },
          { label: '新建', value: '新建' },
        ],
      },
      {
        label: '素材样式',
        mode: 'multiple',
        vModel: 'materialType',
        option: [
          { label: '小图', value: '0' },
          { label: '横板大图', value: 's10' },
          { label: '竖板大图', value: '5s4' },
          { label: '组图', value: '540' },
          { label: '横板视频', value: '550' },
          { label: '竖版视频', value: '054' },
          { label: '穿山甲开屏图片', value: '05433' },
          { label: '直播画面', value: '10' },
          { label: '搜索大图', value: '20' },
          { label: '搜索小图', value: '30' },
          { label: '搜索橱窗', value: '50' },
        ],
      },
      {
        label: '创意方式',
        mode: 'multiple',
        vModel: 'ideaStyle',
        option: [
          { label: '自定义创意', value: '程11s序化创意' },
          { label: '程序化创意', value: '程序化创意' },
        ],
      },
    ],
  },
  {
    id: 'keyword',
    type: '关键词',
    mode: 'default',
    options: [
      {
        label: '关键词状态',
        vModel: 'keywordStatus',
        option: [
          { label: '不限', value: '不限' },
          { label: '词已删除', value: '1' },
          { label: '投放中', value: '3' },
          { label: '词暂停', value: '4' },
          { label: '词审核不通过', value: '5' },
          { label: '词新建不通过', value: '6' },
          { label: '词新建审核中', value: '7' },
          { label: '广告计划已暂停', value: '8' },
          { label: '广告计划审核不通过', value: '9' },
          { label: '广告计划新建审核中', value: '10' },
          { label: '广告计划修改审核中', value: '19' },
          { label: '广告计划超出预算', value: '11' },
          { label: '广告计划新建', value: '12' },
          { label: '广告计划不在投放时间段', value: '13' },
          { label: '广告计划已完成', value: '14' },
          { label: '广告组超出预算', value: '15' },
          { label: '已被广告组暂停', value: '16' },
          { label: '账户余额不足', value: '17' },
          { label: '不限（包含已删除）', value: '18' },
        ],
      },
      {
        label: '匹配方式',
        mode: 'multiple',
        vModel: 'matchType',
        option: [
          { label: '精确', value: '不限' },
          { label: '短语', value: '1' },
          { label: '广泛', value: '3' },
        ],
      },
      {
        label: '质量度',
        mode: 'multiple',
        vModel: 'quality',
        option: [
          { label: '1分', value: '1' },
          { label: '2分', value: '2' },
          { label: '3分', value: '3' },
          { label: '4分', value: '4' },
          { label: '5分', value: '5' },
          { label: '6分', value: '6' },
          { label: '7分', value: '7' },
          { label: '8分', value: '8' },
          { label: '9分', value: '9' },
          { label: '10分', value: '10' },
        ],
      },
    ],
  },
]

// 预算类型
export const BUDGET_TYPE = {
  BUDGET_MODE_INFINITE: '不限',
  BUDGET_MODE_DAY: '日预算',
  BUDGET_MODE_TOTAL: '总预算',
}

// 推广目的类型
export const LANDING_TYPE = {
  LINK: '销售线索收集',
  APP: '应用推广',
  DPA: '商品目录推广',
  GOODS: '商品推广（鲁班）',
  STORE: '门店推广',
  AWEME: '抖音号推广',
  SHOP: '电商店铺推广',
  ARTICAL: '头条文章推广，',
}

// 广告组状态
export const ADGROUP_STATUS = {
  CAMPAIGN_STATUS_ENABLE: '	启用',
  CAMPAIGN_STATUS_DISABLE: '	暂停',
  CAMPAIGN_STATUS_DELETE: '	删除',
  CAMPAIGN_STATUS_ALL: '	所有包含已删除',
  CAMPAIGN_STATUS_NOT_DELETE: ' 所有不包含已删除（状态过滤默认值）',
  CAMPAIGN_STATUS_ADVERTISER_BUDGET_EXCEED: '	超出广告主日预算',
}

// 计划状态
export const PLAN_STATUS = {
  AD_STATUS_DELIVERY_OK: '	投放中',
  AD_STATUS_DISABLE: '	计划暂停',
  AD_STATUS_AUDIT: '	新建审核中',
  AD_STATUS_REAUDIT: '	修改审核中',
  AD_STATUS_DONE: '	已完成',
  AD_STATUS_CREATE: '	计划新建',
  AD_STATUS_AUDIT_DENY: '	审核不通过',
  AD_STATUS_BALANCE_EXCEED: '	账户余额不足',
  AD_STATUS_BUDGET_EXCEED: '	超出预算',
  AD_STATUS_NOT_START: '	未到达投放时间',
  AD_STATUS_NO_SCHEDULE: '	不在投放时段',
  AD_STATUS_CAMPAIGN_DISABLE: '	已被广告组暂停',
  AD_STATUS_CAMPAIGN_EXCEED: '	广告组超出预算',
  AD_STATUS_DELETE: '	已删除',
  AD_STATUS_ALL: '	所有包含已删除',
  AD_STATUS_NOT_DELETE: '	所有不包含已删除',
  AD_STATUS_ADVERTISER_BUDGET_EXCEED: '	超出广告主日预算',
}

// 投放场景-竞价策略 计划投放速度类型
export const FLOW_CONTROL_MODE = {
  FLOW_CONTROL_MODE_FAST: '优先跑量',
  FLOW_CONTROL_MODE_SMOOTH: '优先低成本',
  FLOW_CONTROL_MODE_BALANCE: '均衡投放',
}

// 自动出价类型
export const AUTO_BIG = {
  SMART_BID_CUSTOM: '手动出价',
  SMART_BID_CONSERVATIVE: '自动出价',
}

// 投放范围
export const DELIVERY_RANGE = {
  DEFAULT: '默认',
  UNION: '只投放到资讯联盟（穿山甲）',
  UNIVERSAL: '通投智选',
}

// 投放位置
export const INVENTORY_TYPE = {
  INVENTORY_FEED: '头条',
  INVENTORY_TEXT_LINK: '头条文章详情页（已废弃）',
  INVENTORY_VIDEO_FEED: '西瓜',
  INVENTORY_HOTSOON_FEED: '火山',
  INVENTORY_AWEME_FEED: '抖音',
  INVENTORY_UNION_SLOT: '穿山甲（广告投放）',
  UNION_BOUTIQUE_GAME: '穿山甲精选休闲游戏',
  INVENTORY_UNION_SPLASH_SLOT: '穿山甲开屏广告',
  INVENTORY_AWEME_SEARCH: '搜索广告——抖音位',
  INVENTORY_SEARCH: '搜索广告——头条位',
  INVENTORY_UNIVERSAL: '通投智选',
  INVENTORY_BEAUTY: '轻颜相机',
  INVENTORY_PIPIXIA: '皮皮虾',
}

// 计划投放时间类型
export const SCHEDULE_TYPE = {
  SCHEDULE_FROM_NOW: '从现在开始一直投放',
  SCHEDULE_START_END: '选择起始时间',
}

// 出价 (计划出价类型)
export const PRICING = {
  PRICING_CPC: 'CPC',
  PRICING_CPM: 'CPM',
  PRICING_OCPC: 'oCPC',
  PRICING_OCPM: 'oCPM',
  PRICING_CPV: 'CPV',
  PRICING_CPA: 'CPA',
}

// 投放目标
export const PRICING_TYPE = {
  PRICING_CPC: '点击量',
  PRICING_CPM: '展示数',
  PRICING_OCPC: '转化量',
  PRICING_OCPM: 'oCPM',
  PRICING_CPV: 'CPV',
  PRICING_CPA: 'CPA',
}

// 过滤已转化用户类型
export const FILTER_USER_TYPE = {
  NO_EXCLUDE: '不过滤',
  AD: '广告计划',
  CAMPAIGN: '广告组',
  ADVERTISER: '广告账户',
  APP: 'APP',
  CUSTOMER: '公司账户',
}

// 创意展现方式
export const CREATIVE_DISPLAY_MODE = {
  CREATIVE_DISPLAY_MODE_CTR: '优选',
  CREATIVE_DISPLAY_MODE_RANDOM: '轮播',
}

// 素材类型
export const MATERIAL_TYPR = {
  CREATIVE_IMAGE_MODE_SMALL: '小图',
  CREATIVE_IMAGE_MODE_LARGE: '大图',
  CREATIVE_IMAGE_MODE_GROUP: '组图',
  CREATIVE_IMAGE_MODE_VIDEO: '横板视频',
  CREATIVE_IMAGE_MODE_GIF: 'GIF图',
  CREATIVE_IMAGE_MODE_LARGE_VERTICAL: '大图竖图',
  CREATIVE_IMAGE_MODE_VIDEO_VERTICAL: '竖版视频',
  TOUTIAO_SEARCH_AD_IMAGE: '搜索大图',
  SEARCH_AD_SMALL_IMAGE: '搜索小图',
  CREATIVE_IMAGE_MODE_UNION_SPLASH: '穿山甲开屏图片',
  CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO: '穿山甲开屏视频',
  CREATIVE_IMAGE_MODE_DISPLAY_WINDOW: '搜索橱窗',
  MATERIAL_IMAGE_MODE_TITLE: '标题类型',
  CREATIVE_IMAGE_MODE_AWEME_LIVE: '直播画面类型',
}

// 创意状态
export const CREATIVE_STATUS = {
  CREATIVE_STATUS_DELIVERY_OK: '投放中',
  CREATIVE_STATUS_NOT_START: '未到达投放时间',
  CREATIVE_STATUS_NO_SCHEDULE: '不在投放时段',
  CREATIVE_STATUS_DISABLE: '创意暂停',
  CREATIVE_STATUS_CAMPAIGN_DISABLE: '已被广告组暂停',
  CREATIVE_STATUS_CAMPAIGN_EXCEED: '广告组超出预算',
  CREATIVE_STATUS_AUDIT: '新建审核中',
  CREATIVE_STATUS_REAUDIT: '修改审核中',
  CREATIVE_STATUS_DELETE: '已删除',
  CREATIVE_STATUS_DONE: '已完成',
  CREATIVE_STATUS_AD_DISABLE: '广告计划已暂停',
  CREATIVE_STATUS_AUDIT_DENY: '审核不通过',
  CREATIVE_STATUS_BALANCE_EXCEED: '账户余额不足',
  CREATIVE_STATUS_BUDGET_EXCEED: '超出预算',
  CREATIVE_STATUS_DATA_ERROR: '数据错误',
}

// 广告创意状态
export const advertisingStatu = {
  CREATIVE_STATUS_DELIVERY_OK: '投放中',
  CREATIVE_STATUS_NOT_START: '未到达投放时间',
  CREATIVE_STATUS_NO_SCHEDULE: '不在投放时段',
  CREATIVE_STATUS_DISABLE: '创意暂停',
  CREATIVE_STATUS_DONE: '已完成',
  CREATIVE_STATUS_DELETE: '已删除',
  CREATIVE_STATUS_AD_DISABLE: '广告计划暂停',
  CREATIVE_STATUS_AUDIT_DENY: '审核不通过',
  CREATIVE_STATUS_BALANCE_EXCEED: '账户余额不足',
  CREATIVE_STATUS_BUDGET_EXCEED: '超出预算',
  CREATIVE_STATUS_DATA_ERROR: '数据错误',
  CREATIVE_STATUS_PRE_ONLINE: '预上线',
  CREATIVE_STATUS_AD_AUDIT: '广告计划新建审核中',
  CREATIVE_STATUS_AD_REAUDIT: '广告计划修改审核中',
  CREATIVE_STATUS_AD_AUDIT_DENY: '广告计划审核不通过',
  CREATIVE_STATUS_ALL: '所有包含已删除',
  CREATIVE_STATUS_NOT_DELETE: '所有不包含已删除',
  CREATIVE_STATUS_ADVERTISER_BUDGET_EXCEED: '超出账户日预算',
}

// 广告组类型
export const advertisingsStatu = {
  FEED: '信息流',
}

// 创意搜索筛选 —— 分类
export const IDEA_FILTER_ORDER = {
  1: '展示数高到低',
  2: '展示数低到高',
  COST_DESC: '消耗高到低',
  COST_ASC: '消耗低到高',
  3: '转化数高到低',
  4: '转化数低到高',
  AVG_CLICK_COST_DESC: '转化率高到低',
  AVG_CLICK_COST_ASC: '转化率低到高',

  // CONVERT_DESC: '为转化数高到低',
  // CONVERT_ASC: '消耗为从低到高',
  // CONVERT_COST_DESC: '为转化成本高到低',
  // CONVERT_COST_ASC: '转化成本为从低到高',
  // AVG_CLICK_COST_DESC: '为平均点击单价高到低',
  // AVG_CLICK_COST_ASC: '平均点击单价为从低到高',
}

// 创意搜索条件 —— 状态
export const IDES_FILTER_STATUS = {
  0: '不限',
  1: '投放中',
  2: '审核不通过',
  3: '不在投放时段',
  4: '已暂停',
  5: '已被广告组暂停',
  6: '广告计划超出预期',
  7: '广告组超出预算',
  8: '账号余额不足',
  9: '新建审核中',
  10: '修改审核中',
  11: '已删除',
  12: '已完成',
  13: '未达到投放时间',
  14: '不限（包含已删除）',
}
