/*
 * @Author: lizheng
 * @Date: 2021-03-06 10:53:10
 * @LastEditTime: 2021-10-18 13:58:17
 * @LastEditors: Please set LastEditors
 * @Description: table column 以及常量数据
 * @FilePath: \ads\pages\statement\production-statment\columns.js
 */
export const advertisingColumns = [
  {
    title: '时间',
    dataIndex: 'hour',
    key: 'hour',
    width: 160,
    ellipsis: true,
    fixed: 'left',
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '销售额',
    dataIndex: 'sales',
    key: 'sales',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '总消耗',
    dataIndex: 'totalCost',
    key: 'totalCost',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '总成交',
    dataIndex: 'totalDeal',
    key: 'totalDeal',
    width: 120,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '总ROI',
    dataIndex: 'totalRoi',
    key: 'totalRoi',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '基础销量',
    dataIndex: 'basicsSales',
    key: 'basicsSales',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '巨量',
    // dataIndex: 'ctr1',
    // key: 'ctr1',
    width: 360,
    ellipsis: true,
    customHeaderCell: () => ({ style: { height: '47px' } }),
    // customRender: (text) => (text ? `${(Number(text) * 100).toFixed(2)}  %` : ''),
    children: [
      {
        title: '消耗',
        dataIndex: 'oceanCost',
        key: 'oceanCost',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: '成交',
        dataIndex: 'oceanDeal',
        key: 'oceanDeal',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: 'ROI',
        dataIndex: 'oceanRoi',
        key: 'oceanRoi',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
    ],
  },
  {
    title: '快手',
    // dataIndex: 'convertCost1',
    // key: 'convertCost1',
    width: 360,
    ellipsis: true,
    customHeaderCell: () => ({ style: { height: '47px' } }),
    children: [
      {
        title: '消耗',
        dataIndex: 'quickWorkerCost',
        key: 'quickWorkerCost',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: '成交',
        dataIndex: 'quickWorkerDeal',
        key: 'quickWorkerDeal',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: 'ROI',
        dataIndex: 'quickWorkerRoi',
        key: 'quickWorkerRoi',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
    ],
  },
  {
    title: '微博',
    // dataIndex: 'deepConvertRate1',
    // key: 'deepConvertRate1',
    width: 360,
    ellipsis: true,
    customHeaderCell: () => ({ style: { height: '47px' } }),
    // customRender: (text) => (text ? `${(Number(text) * 100).toFixed(2)}  %` : ''),
    children: [
      {
        title: '消耗',
        dataIndex: 'microBlogCost',
        key: 'microBlogCost',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: '成交',
        dataIndex: 'microBlogDeal',
        key: 'microBlogDeal',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: 'ROI',
        dataIndex: 'microBlogRoi',
        key: 'microBlogRoi',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
    ],
  },
  {
    title: '抖音UD',
    // dataIndex: 'convert1',
    // key: 'convert1',
    width: 360,
    ellipsis: true,
    customHeaderCell: () => ({ style: { height: '47px' } }),
    children: [
      {
        title: '消耗',
        dataIndex: 'douYinUdCost',
        key: 'douYinUdCost',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: '成交',
        dataIndex: 'douYinUdDeal',
        key: 'douYinUdDeal',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: 'ROI',
        dataIndex: 'douYinUdRoi',
        key: 'douYinUdRoi',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
    ],
  },
  {
    title: '快手UD',
    // dataIndex: 'convertRate1',
    // key: 'convertRate1',
    width: 360,
    ellipsis: true,
    customHeaderCell: () => ({ style: { height: '47px' } }),
    // customRender: (text) => (text ? `${(Number(text) * 100).toFixed(2)}  %` : ''),
    children: [
      {
        title: '消耗',
        dataIndex: 'quickWorkerUdCost',
        key: 'quickWorkerUdCost',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: '成交',
        dataIndex: 'quickWorkerUdDeal',
        key: 'quickWorkerUdDeal',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: 'ROI',
        dataIndex: 'quickWorkerUdRoi',
        key: 'quickWorkerUdRoi',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
    ],
  },
  {
    title: '腾讯UD',
    // dataIndex: 'tencentUdCost',
    // key: 'tencentUdCost',
    width: 360,
    ellipsis: true,
    customHeaderCell: () => ({ style: { height: '47px' } }),
    children: [
      {
        title: '消耗',
        dataIndex: 'tencentUdCost',
        key: 'tencentUdCost',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: '成交',
        dataIndex: 'tencentUdDeal',
        key: 'tencentUdDeal',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: 'ROI',
        dataIndex: 'tencentUdRoi',
        key: 'tencentUdRoi',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
    ],
  },
  {
    title: '抖音内容服务',
    // dataIndex: 'douYinContentServe',
    // key: 'douYinContentServe',
    width: 360,
    ellipsis: true,
    customHeaderCell: () => ({ style: { height: '47px' } }),
    children: [
      {
        title: '消耗',
        dataIndex: 'douYinContentServeCost',
        key: 'douYinContentServeCost',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: '成交',
        dataIndex: 'douYinContentServeDeal',
        key: 'douYinContentServeDeal',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: 'ROI',
        dataIndex: 'douYinContentServeRoi',
        key: 'douYinContentServeRoi',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
    ],
  },
  {
    title: '抖音内容热推',
    // dataIndex: 'roi',
    // key: 'roi',
    width: 360,
    ellipsis: true,
    customHeaderCell: () => ({ style: { height: '47px' } }),
    children: [
      {
        title: '消耗',
        dataIndex: 'douYinContentPushCost',
        key: 'douYinContentPushCost',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: '成交',
        dataIndex: 'douYinContentPushDeal',
        key: 'douYinContentPushDeal',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: 'ROI',
        dataIndex: 'douYinContentPushRoi',
        key: 'douYinContentPushRoi',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
    ],
  },
  {
    title: '快手优推',
    // dataIndex: 'sellPrice',
    // key: 'sellPrice',
    width: 360,
    ellipsis: true,
    customHeaderCell: () => ({ style: { height: '47px' } }),
    children: [
      {
        title: '消耗',
        dataIndex: 'quickWorkerPushCost',
        key: 'quickWorkerPushCost',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: '成交',
        dataIndex: 'quickWorkerPushDeal',
        key: 'quickWorkerPushDeal',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
      {
        title: 'ROI',
        dataIndex: 'quickWorkerPushRoi',
        key: 'quickWorkerPushRoi',
        width: 120,
        ellipsis: true,
        align: 'center',
      },
    ],
  },
  // {
  //   title: '浏览量',
  //   dataIndex: 'view',
  //   key: 'view',
  //   width: 100,
  //   ellipsis: true,
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },
  // {
  //   title: '访客数',
  //   dataIndex: 'visited',
  //   key: 'visited',
  //   width: 100,
  //   ellipsis: true,
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },
  // {
  //   title: '销量',
  //   dataIndex: 'sales',
  //   key: 'sales',
  //   width: 100,
  //   ellipsis: true,
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },
  // {
  //   title: '订单数',
  //   dataIndex: 'orderCount',
  //   key: 'orderCount',
  //   width: 100,
  //   ellipsis: true,
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },

  // {
  //   title: '入口数',
  //   dataIndex: 'entrance',
  //   key: 'entrance',
  //   width: 100,
  //   ellipsis: true,
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },
  // {
  //   title: '跳失率',
  //   dataIndex: 'skipRate',
  //   key: 'skipRate',
  //   width: 100,
  //   ellipsis: true,
  //   customRender: (text) => (text ? `${(Number(text) * 100).toFixed(2)}  %` : ''),
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },
  // {
  //   title: '停留时间',
  //   dataIndex: 'stopTime',
  //   key: 'stopTime',
  //   width: 100,
  //   ellipsis: true,
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },
  // {
  //   title: '收藏',
  //   dataIndex: 'favorites',
  //   key: 'favorites',
  //   width: 100,
  //   ellipsis: true,
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },
  // {
  //   title: '购物车',
  //   dataIndex: 'shopCart',
  //   key: 'shopCart',
  //   width: 100,
  //   ellipsis: true,
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },
  // {
  //   title: '搜索UV',
  //   dataIndex: 'searchUv',
  //   key: 'searchUv',
  //   width: 100,
  //   ellipsis: true,
  //   customHeaderCell: () => ({ style: { height: '47px' } }),
  // },
]
