import { center } from '@antv/g2plot/lib/plots/sankey/sankey'

/*
 * @Author: lizheng
 * @Date: 2021-03-06 10:53:10
 * @LastEditTime: 2021-10-16 16:14:37
 * @LastEditors: Please set LastEditors
 * @Description: table column 以及常量数据
 * @FilePath: \ads\pages\statement\production-statment\columns.js
 */
export const productColumns = [
  {
    title: '日期',
    dataIndex: 'date',
    key: 'date',
    width: 160,
    ellipsis: true,
    fixed: 'left',
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '浏览量',
    dataIndex: 'view',
    key: 'view',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '访客数',
    dataIndex: 'visited',
    key: 'visited',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '销售额',
    dataIndex: 'sellPrice',
    key: 'sellPrice',
    width: 120,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '销量',
    dataIndex: 'sales',
    key: 'sales',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '订单数',
    dataIndex: 'orderCount',
    key: 'orderCount',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '转化率',
    dataIndex: 'convertRate',
    key: 'convertRate',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
    // customRender: (text) => (text ? `${(Number(text) * 100).toFixed(2)}  %` : ''),
  },
  {
    title: '客单价',
    dataIndex: 'customerPrice',
    key: 'customerPrice',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '入口数',
    dataIndex: 'entrance',
    key: 'entrance',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
    // customRender: (text) => (text ? `${(Number(text) * 100).toFixed(2)}  %` : ''),
  },
  {
    title: '跳失率',
    dataIndex: 'skipRate',
    key: 'skipRate',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '停留时间',
    dataIndex: 'stopTime',
    key: 'stopTime',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
    // customRender: (text) => (text ? `${(Number(text) * 100).toFixed(2)}  %` : ''),
  },
  {
    title: '收藏',
    dataIndex: 'favorites',
    key: 'favorites',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '购物车',
    dataIndex: 'shopCart',
    key: 'shopCart',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '搜索UV',
    dataIndex: 'roi',
    key: 'roi',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '大盘人气',
    dataIndex: 'popularity',
    key: 'popularity',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '核访客',
    dataIndex: 'nuclearVisitors',
    key: 'nuclearVisitors',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '支付件数',
    dataIndex: 'payNumber',
    key: 'payNumber',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '支付买家数',
    dataIndex: 'payBuyerNumber',
    key: 'payBuyerNumber',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '支付转化率',
    dataIndex: 'payConvertRate',
    key: 'payConvertRate',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },

  {
    title: '泛访客',
    dataIndex: 'genericVisitors',
    key: 'genericVisitors',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '泛买家数',
    dataIndex: 'genericBuyerNumber',
    key: 'genericBuyerNumber',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '泛转化率',
    dataIndex: 'genericConvertRate',
    key: 'genericConvertRate',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '淘排名',
    dataIndex: 'ranking',
    key: 'ranking',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '售价',
    dataIndex: 'sellingPrice',
    key: 'sellingPrice',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '运营概述',
    dataIndex: 'overview',
    key: 'overview',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '活动',
    dataIndex: 'activity',
    key: 'activity',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '广告消耗',
    dataIndex: 'cost',
    key: 'cost',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
  {
    title: '广告占比',
    dataIndex: 'ratio',
    key: 'ratio',
    width: 120,
    ellipsis: true,
    align: 'center',
    customHeaderCell: () => ({ style: { height: '47px' } }),
  },
]
